using Microsoft.EntityFrameworkCore;
using RouteWeather.Data.Entities;

namespace RouteWeather.Data;

public static class RouteSeeder
{
    public static async Task SeedAsync(RouteWeatherContext db, CancellationToken ct = default)
    {
        if (await db.Routes.AnyAsync(ct)) return;

        db.Routes.AddRange(Colorado14ers());

        await db.SaveChangesAsync(ct);
    }

    // The 58 Colorado 14ers (14ers.com climber's list) with their standard routes.
    // Lat/lon are summit coordinates. SNOTEL station triplets are hand-picked nearest
    // representative stations; the aggregator tolerates SNOTEL failures gracefully.
    private static IEnumerable<RouteEntity> Colorado14ers() => new[]
    {
        new RouteEntity { Slug = "mount-elbert",           Mountain = "Mount Elbert",           RouteName = "Northeast Ridge",                SummitElevationFt = 14438, SummitLat = 39.1178, SummitLon = -106.4453, ClassDifficulty = "1", SnotelStationTriplet = "369:CO:SNTL" },
        new RouteEntity { Slug = "mount-massive",          Mountain = "Mount Massive",          RouteName = "East Slopes",                    SummitElevationFt = 14428, SummitLat = 39.1873, SummitLon = -106.4756, ClassDifficulty = "2", SnotelStationTriplet = "1101:CO:SNTL" },
        new RouteEntity { Slug = "mount-harvard",          Mountain = "Mount Harvard",          RouteName = "South Slopes",                   SummitElevationFt = 14421, SummitLat = 38.9244, SummitLon = -106.3206, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "blanca-peak",            Mountain = "Blanca Peak",            RouteName = "Northwest Ridge",                SummitElevationFt = 14345, SummitLat = 37.5775, SummitLon = -105.4856, ClassDifficulty = "2", SnotelStationTriplet = "1141:CO:SNTL" },
        new RouteEntity { Slug = "la-plata-peak",          Mountain = "La Plata Peak",          RouteName = "Northwest Ridge",                SummitElevationFt = 14336, SummitLat = 39.0294, SummitLon = -106.4729, ClassDifficulty = "2", SnotelStationTriplet = "369:CO:SNTL" },
        new RouteEntity { Slug = "uncompahgre-peak",       Mountain = "Uncompahgre Peak",       RouteName = "South Ridge",                    SummitElevationFt = 14309, SummitLat = 38.0717, SummitLon = -107.4622, ClassDifficulty = "2", SnotelStationTriplet = "1186:CO:SNTL" },
        new RouteEntity { Slug = "crestone-peak",          Mountain = "Crestone Peak",          RouteName = "South Face (Red Gully)",         SummitElevationFt = 14294, SummitLat = 37.9669, SummitLon = -105.5853, ClassDifficulty = "3", SnotelStationTriplet = "1128:CO:SNTL" },
        new RouteEntity { Slug = "mount-lincoln",          Mountain = "Mount Lincoln",          RouteName = "West Ridge (DeCaLiBron)",        SummitElevationFt = 14286, SummitLat = 39.3514, SummitLon = -106.1117, ClassDifficulty = "2", SnotelStationTriplet = "1120:CO:SNTL" },
        new RouteEntity { Slug = "grays-peak",             Mountain = "Grays Peak",             RouteName = "North Slopes",                   SummitElevationFt = 14270, SummitLat = 39.6339, SummitLon = -105.8175, ClassDifficulty = "1", SnotelStationTriplet = "1187:CO:SNTL" },
        new RouteEntity { Slug = "mount-antero",           Mountain = "Mount Antero",           RouteName = "West Slopes (Baldwin Gulch)",    SummitElevationFt = 14269, SummitLat = 38.6741, SummitLon = -106.2461, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "torreys-peak",           Mountain = "Torreys Peak",           RouteName = "South Slopes (via Grays)",       SummitElevationFt = 14267, SummitLat = 39.6428, SummitLon = -105.8211, ClassDifficulty = "2", SnotelStationTriplet = "1187:CO:SNTL" },
        new RouteEntity { Slug = "castle-peak",            Mountain = "Castle Peak",            RouteName = "Northeast Ridge",                SummitElevationFt = 14265, SummitLat = 39.0094, SummitLon = -106.8614, ClassDifficulty = "2", SnotelStationTriplet = "542:CO:SNTL" },
        new RouteEntity { Slug = "quandary-peak",          Mountain = "Quandary Peak",          RouteName = "East Ridge",                     SummitElevationFt = 14265, SummitLat = 39.3973, SummitLon = -106.1064, ClassDifficulty = "1", SnotelStationTriplet = "1120:CO:SNTL" },
        new RouteEntity { Slug = "mount-evans",            Mountain = "Mount Evans",            RouteName = "Northeast Face",                 SummitElevationFt = 14264, SummitLat = 39.5883, SummitLon = -105.6438, ClassDifficulty = "2", SnotelStationTriplet = "1187:CO:SNTL" },
        new RouteEntity { Slug = "longs-peak",             Mountain = "Longs Peak",             RouteName = "Keyhole",                        SummitElevationFt = 14255, SummitLat = 40.2549, SummitLon = -105.6160, ClassDifficulty = "3", SnotelStationTriplet = "1042:CO:SNTL" },
        new RouteEntity { Slug = "mount-wilson",           Mountain = "Mount Wilson",           RouteName = "North Slopes",                   SummitElevationFt = 14246, SummitLat = 37.8389, SummitLon = -107.9911, ClassDifficulty = "4", SnotelStationTriplet = "1060:CO:SNTL" },
        new RouteEntity { Slug = "mount-cameron",          Mountain = "Mount Cameron",          RouteName = "DeCaLiBron via saddle",          SummitElevationFt = 14238, SummitLat = 39.3464, SummitLon = -106.1186, ClassDifficulty = "2", SnotelStationTriplet = "1120:CO:SNTL" },
        new RouteEntity { Slug = "mount-shavano",          Mountain = "Mount Shavano",          RouteName = "East Slopes (Angel of Shavano)", SummitElevationFt = 14229, SummitLat = 38.6192, SummitLon = -106.2253, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "mount-belford",          Mountain = "Mount Belford",          RouteName = "Northwest Ridge",                SummitElevationFt = 14197, SummitLat = 38.9606, SummitLon = -106.3608, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "crestone-needle",        Mountain = "Crestone Needle",        RouteName = "South Face",                     SummitElevationFt = 14197, SummitLat = 37.9647, SummitLon = -105.5764, ClassDifficulty = "3", SnotelStationTriplet = "1128:CO:SNTL" },
        new RouteEntity { Slug = "mount-princeton",        Mountain = "Mount Princeton",        RouteName = "East Slopes",                    SummitElevationFt = 14197, SummitLat = 38.7492, SummitLon = -106.2425, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "mount-yale",             Mountain = "Mount Yale",             RouteName = "Southwest Slopes",               SummitElevationFt = 14196, SummitLat = 38.8442, SummitLon = -106.3136, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "mount-bross",            Mountain = "Mount Bross",            RouteName = "West Slopes (DeCaLiBron)",       SummitElevationFt = 14172, SummitLat = 39.3358, SummitLon = -106.1078, ClassDifficulty = "2", SnotelStationTriplet = "1120:CO:SNTL" },
        new RouteEntity { Slug = "kit-carson-peak",        Mountain = "Kit Carson Peak",        RouteName = "North Ridge (via Challenger)",   SummitElevationFt = 14165, SummitLat = 37.9794, SummitLon = -105.6028, ClassDifficulty = "3", SnotelStationTriplet = "1128:CO:SNTL" },
        new RouteEntity { Slug = "el-diente-peak",         Mountain = "El Diente Peak",         RouteName = "North Slopes",                   SummitElevationFt = 14159, SummitLat = 37.8394, SummitLon = -108.0050, ClassDifficulty = "3", SnotelStationTriplet = "1060:CO:SNTL" },
        new RouteEntity { Slug = "maroon-peak",            Mountain = "Maroon Peak",            RouteName = "South Ridge",                    SummitElevationFt = 14156, SummitLat = 39.0708, SummitLon = -106.9889, ClassDifficulty = "4", SnotelStationTriplet = "542:CO:SNTL" },
        new RouteEntity { Slug = "tabeguache-peak",        Mountain = "Tabeguache Peak",        RouteName = "West Ridge (via Shavano)",       SummitElevationFt = 14155, SummitLat = 38.6258, SummitLon = -106.2386, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "mount-oxford",           Mountain = "Mount Oxford",           RouteName = "West Ridge (via Belford)",       SummitElevationFt = 14153, SummitLat = 38.9647, SummitLon = -106.3389, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "mount-sneffels",         Mountain = "Mount Sneffels",         RouteName = "Southwest Ridge (Lavender Col)", SummitElevationFt = 14150, SummitLat = 38.0036, SummitLon = -107.7925, ClassDifficulty = "3", SnotelStationTriplet = "1186:CO:SNTL" },
        new RouteEntity { Slug = "mount-democrat",         Mountain = "Mount Democrat",         RouteName = "East Slopes (DeCaLiBron)",       SummitElevationFt = 14148, SummitLat = 39.3394, SummitLon = -106.1397, ClassDifficulty = "2", SnotelStationTriplet = "1120:CO:SNTL" },
        new RouteEntity { Slug = "capitol-peak",           Mountain = "Capitol Peak",           RouteName = "Northeast Ridge (Knife Edge)",   SummitElevationFt = 14130, SummitLat = 39.1503, SummitLon = -107.0830, ClassDifficulty = "4", SnotelStationTriplet = "542:CO:SNTL" },
        new RouteEntity { Slug = "pikes-peak",             Mountain = "Pikes Peak",             RouteName = "Barr Trail",                     SummitElevationFt = 14110, SummitLat = 38.8409, SummitLon = -105.0442, ClassDifficulty = "1", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "snowmass-mountain",      Mountain = "Snowmass Mountain",      RouteName = "East Slopes",                    SummitElevationFt = 14092, SummitLat = 39.1186, SummitLon = -107.0664, ClassDifficulty = "3", SnotelStationTriplet = "542:CO:SNTL" },
        new RouteEntity { Slug = "mount-eolus",            Mountain = "Mount Eolus",            RouteName = "Northeast Ridge",                SummitElevationFt = 14083, SummitLat = 37.6219, SummitLon = -107.6225, ClassDifficulty = "3", SnotelStationTriplet = "1060:CO:SNTL" },
        new RouteEntity { Slug = "windom-peak",            Mountain = "Windom Peak",            RouteName = "West Ridge",                     SummitElevationFt = 14082, SummitLat = 37.6214, SummitLon = -107.5917, ClassDifficulty = "2", SnotelStationTriplet = "1060:CO:SNTL" },
        new RouteEntity { Slug = "challenger-point",       Mountain = "Challenger Point",       RouteName = "North Slopes",                   SummitElevationFt = 14081, SummitLat = 37.9803, SummitLon = -105.6064, ClassDifficulty = "2", SnotelStationTriplet = "1128:CO:SNTL" },
        new RouteEntity { Slug = "mount-columbia",         Mountain = "Mount Columbia",         RouteName = "West Slopes",                    SummitElevationFt = 14077, SummitLat = 38.9039, SummitLon = -106.2972, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "missouri-mountain",      Mountain = "Missouri Mountain",      RouteName = "Northwest Ridge",                SummitElevationFt = 14074, SummitLat = 38.9478, SummitLon = -106.3789, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "humboldt-peak",          Mountain = "Humboldt Peak",          RouteName = "West Ridge",                     SummitElevationFt = 14070, SummitLat = 37.9764, SummitLon = -105.5550, ClassDifficulty = "2", SnotelStationTriplet = "1128:CO:SNTL" },
        new RouteEntity { Slug = "mount-bierstadt",        Mountain = "Mount Bierstadt",        RouteName = "West Slopes",                    SummitElevationFt = 14065, SummitLat = 39.5828, SummitLon = -105.6685, ClassDifficulty = "2", SnotelStationTriplet = "1187:CO:SNTL" },
        new RouteEntity { Slug = "conundrum-peak",         Mountain = "Conundrum Peak",         RouteName = "Northeast Ridge (via Castle)",   SummitElevationFt = 14060, SummitLat = 39.0064, SummitLon = -106.8675, ClassDifficulty = "2", SnotelStationTriplet = "542:CO:SNTL" },
        new RouteEntity { Slug = "sunlight-peak",          Mountain = "Sunlight Peak",          RouteName = "South Face",                     SummitElevationFt = 14059, SummitLat = 37.6275, SummitLon = -107.5950, ClassDifficulty = "4", SnotelStationTriplet = "1060:CO:SNTL" },
        new RouteEntity { Slug = "handies-peak",           Mountain = "Handies Peak",           RouteName = "American Basin",                 SummitElevationFt = 14048, SummitLat = 37.9131, SummitLon = -107.5042, ClassDifficulty = "2", SnotelStationTriplet = "1186:CO:SNTL" },
        new RouteEntity { Slug = "culebra-peak",           Mountain = "Culebra Peak",           RouteName = "Northwest Ridge",                SummitElevationFt = 14047, SummitLat = 37.1225, SummitLon = -105.1856, ClassDifficulty = "2", SnotelStationTriplet = "1141:CO:SNTL" },
        new RouteEntity { Slug = "ellingwood-point",       Mountain = "Ellingwood Point",       RouteName = "South Face (via Blanca)",        SummitElevationFt = 14042, SummitLat = 37.5822, SummitLon = -105.4925, ClassDifficulty = "2", SnotelStationTriplet = "1141:CO:SNTL" },
        new RouteEntity { Slug = "mount-lindsey",          Mountain = "Mount Lindsey",          RouteName = "Northwest Ridge",                SummitElevationFt = 14042, SummitLat = 37.5836, SummitLon = -105.4456, ClassDifficulty = "2", SnotelStationTriplet = "1141:CO:SNTL" },
        new RouteEntity { Slug = "north-eolus",            Mountain = "North Eolus",            RouteName = "Eolus Ridge",                    SummitElevationFt = 14039, SummitLat = 37.6228, SummitLon = -107.6233, ClassDifficulty = "3", SnotelStationTriplet = "1060:CO:SNTL" },
        new RouteEntity { Slug = "little-bear-peak",       Mountain = "Little Bear Peak",       RouteName = "West Ridge (Hourglass)",         SummitElevationFt = 14037, SummitLat = 37.5667, SummitLon = -105.4972, ClassDifficulty = "4", SnotelStationTriplet = "1141:CO:SNTL" },
        new RouteEntity { Slug = "mount-sherman",          Mountain = "Mount Sherman",          RouteName = "Southwest Ridge",                SummitElevationFt = 14036, SummitLat = 39.2253, SummitLon = -106.1697, ClassDifficulty = "2", SnotelStationTriplet = "1120:CO:SNTL" },
        new RouteEntity { Slug = "redcloud-peak",          Mountain = "Redcloud Peak",          RouteName = "Northeast Ridge",                SummitElevationFt = 14034, SummitLat = 37.9408, SummitLon = -107.4214, ClassDifficulty = "2", SnotelStationTriplet = "1186:CO:SNTL" },
        new RouteEntity { Slug = "pyramid-peak",           Mountain = "Pyramid Peak",           RouteName = "Northeast Ridge",                SummitElevationFt = 14018, SummitLat = 39.0716, SummitLon = -106.9501, ClassDifficulty = "4", SnotelStationTriplet = "542:CO:SNTL" },
        new RouteEntity { Slug = "wilson-peak",            Mountain = "Wilson Peak",            RouteName = "West Ridge",                     SummitElevationFt = 14017, SummitLat = 37.8597, SummitLon = -107.9847, ClassDifficulty = "3", SnotelStationTriplet = "1060:CO:SNTL" },
        new RouteEntity { Slug = "wetterhorn-peak",        Mountain = "Wetterhorn Peak",        RouteName = "Southeast Ridge",                SummitElevationFt = 14015, SummitLat = 38.0606, SummitLon = -107.5106, ClassDifficulty = "3", SnotelStationTriplet = "1186:CO:SNTL" },
        new RouteEntity { Slug = "north-maroon-peak",      Mountain = "North Maroon Peak",      RouteName = "Northeast Ridge",                SummitElevationFt = 14014, SummitLat = 39.0758, SummitLon = -106.9883, ClassDifficulty = "4", SnotelStationTriplet = "542:CO:SNTL" },
        new RouteEntity { Slug = "san-luis-peak",          Mountain = "San Luis Peak",          RouteName = "Northeast Ridge",                SummitElevationFt = 14014, SummitLat = 37.9869, SummitLon = -106.9311, ClassDifficulty = "2", SnotelStationTriplet = "1186:CO:SNTL" },
        new RouteEntity { Slug = "mount-of-the-holy-cross", Mountain = "Mount of the Holy Cross", RouteName = "North Ridge",                  SummitElevationFt = 14005, SummitLat = 39.4669, SummitLon = -106.4814, ClassDifficulty = "2", SnotelStationTriplet = "1101:CO:SNTL" },
        new RouteEntity { Slug = "huron-peak",             Mountain = "Huron Peak",             RouteName = "Northwest Slopes",               SummitElevationFt = 14003, SummitLat = 38.9453, SummitLon = -106.4378, ClassDifficulty = "2", SnotelStationTriplet = "1057:CO:SNTL" },
        new RouteEntity { Slug = "sunshine-peak",          Mountain = "Sunshine Peak",          RouteName = "North Slopes (via Redcloud)",    SummitElevationFt = 14001, SummitLat = 37.9258, SummitLon = -107.4256, ClassDifficulty = "2", SnotelStationTriplet = "1186:CO:SNTL" },
    };
}
